/** The site's pages, shared by the e2e specs. */
export const PAGES = [
  "/",
  "/explore",
  "/matrix",
  "/what-if",
  "/learn",
  "/method",
  "/about",
  "/learn/01-batching-and-chunked-prefill",
  "/learn/02-paged-kv-and-preemption",
  "/learn/03-prefix-caching",
  "/learn/04-disaggregation",
  "/learn/05-heterogeneous-and-optical-pools",
  "/learn/06-kv-handoff-and-compression",
  "/learn/07-encoder-only-prefill",
  "/learn/08-tp-pp-ep",
  "/learn/09-quantisation",
  "/learn/10-speculative-decoding",
  "/learn/11-power-and-energy",
  "/learn/12-hardware-and-cost",
  "/learn/13-combining-levers",
  "/workloads",
  "/workloads/chat",
  "/workloads/coding-agent",
  "/workloads/offline-batch",
  "/workloads/long-rag",
  "/workloads/voice",
];

/** [page, test id] of every animation. */
export const ANIMATIONS = [
  ["/", "hero-home"],
  ["/explore", "explorer"],
  ["/matrix", "matrix"],
  ["/learn/01-batching-and-chunked-prefill", "lever-matrix"],
  ["/what-if", "timeline"],
  // the chapters' mechanism animations (recorded by the simulator, or its cost model live)
  ["/learn/01-batching-and-chunked-prefill", "mech-batching"],
  ["/learn/02-paged-kv-and-preemption", "mech-kv"],
  ["/learn/03-prefix-caching", "mech-prefix"],
  ["/learn/04-disaggregation", "mech-pools"],
  ["/learn/05-heterogeneous-and-optical-pools", "mech-hetero"],
  ["/learn/06-kv-handoff-and-compression", "mech-handoff"],
  ["/learn/07-encoder-only-prefill", "mech-ced"],
  ["/learn/08-tp-pp-ep", "mech-ring"],
  ["/learn/08-tp-pp-ep", "mech-gpipe"],
  ["/learn/09-quantisation", "mech-bytes"],
  ["/learn/10-speculative-decoding", "mech-spec"],
  ["/learn/11-power-and-energy", "mech-power"],
  ["/learn/12-hardware-and-cost", "mech-cost"],
  ["/learn/13-combining-levers", "mech-combine"],
  ["/workloads/chat", "case-explorer"],
] as const;
